"""Generate a LaTeX results table from the committed summary CSV."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

from aed.utils import ensure_parent


def generate(input_path="results/summary/summary.csv", output="paper/tables/results_table.tex"):
    with Path(input_path).open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    lines = [
        "% Generated by analysis/generate_paper_table.py; do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Stochastic corridor results over independent seeds.}",
        "\\label{tab:corridor-results}",
        "\\begin{tabular}{lrrr}",
        "\\toprule",
        "Method & Room A occupancy & Escape time & External reward \\\\",
        "\\midrule",
    ]
    for row in rows:
        method = row["method"]
        occupancy = f'{float(row["occ_0_mean"]):.3f} $\\pm$ {float(row["occ_0_std"]):.3f}'
        escape = f'{float(row["escape_time_mean"]):.1f} $\\pm$ {float(row["escape_time_std"]):.1f}'
        reward = f'{float(row["external_reward_mean"]):.1f} $\\pm$ {float(row["external_reward_std"]):.1f}'
        lines.append(f"{method} & {occupancy} & {escape} & {reward} \\\\")
    lines.extend(["\\bottomrule", "\\end{tabular}", "\\end{table}", ""])
    target = ensure_parent(output)
    target.write_text("\n".join(lines), encoding="utf-8")
    return target


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", default="results/summary/summary.csv")
    parser.add_argument("--output", default="paper/tables/results_table.tex")
    args = parser.parse_args(argv)
    print(f"wrote {generate(args.input, args.output)}")


if __name__ == "__main__":
    main()
